apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
  labels:
    name: pod-volume
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
      - mountPath: /volume-dentro-do-container
        name: primeiro-volume
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: jenkins-container
    image: jenkins:alpine
    volumeMounts:
      - mountPath: /volume-dentro-do-container
        name: primeiro-volume
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
    - name: primeiro-volume
      hostPath:
        path: /home/guilherme/estudo/infra/primeiro-volume
        type: DirectoryOrCreate